# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 457ecf9f0baf19fdd534c58c37f846f138876dd01f81af2a8bee02d95ac7c5fe0c22edab272811639521d55fcda72fb628d2aba236bbae5320f887b1509b4f57

test:
  secret_key_base: c048fb99d8ab49b466ffaede5087f906739e0c233593b4b1cd34e42ded1448b1d14be0e16eee4da38fd238eb1b63e331b5b766b28b61f8dc7b5a0959e61d872d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["TURTLECAMP_SECRET_KEY_BASE"] %>
